In [14]:
import numpy as np
dataset = np.loadtxt('datasets-part1/tictac_final.txt')


In [15]:
np.random.shuffle(dataset)

In [16]:
X = dataset[:, :9]
Y = dataset[:,9:]

In [17]:
print(X.shape)
print(Y.shape)

(958, 9)
(958, 1)


In [18]:
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix

In [19]:
def MLP(train_X, test_X, train_Y, test_Y):
    n_neighbors = 15
    print(test_X.shape)
    print(test_Y.shape)
    
    clf = MLPClassifier(random_state=1, max_iter=300)
    clf.fit(train_X, train_Y)
    res = clf.predict(test_X)
    res_cm = res
    res = np.asarray(res)
    res = np.reshape(res, (-1, test_Y.shape[0]))
    accuracy = 0.0
    for i in range(res.shape[1]):
        if(res[0][i] == test_Y[i][0]):
            accuracy += 1
    print(accuracy)
    print("Accuracy = " + str(accuracy/res.shape[1]))
    print("#### CONFUSION MATRIX ##########")
    cm = confusion_matrix(test_Y, res_cm)
    cm = cm / cm.sum(axis=1)[:, np.newaxis]
    print(cm)
    return accuracy/res.shape[1], clf

In [20]:
#train_X = X[0:800]
#test_X = X[800:958]
#train_Y = Y[0:800]
#test_Y = Y[800:958]

#print(test_Y.shape)
#print(test_Y)
#k fold validation
#k_cross_fold = 1

#res = linearSVM(train_X, test_X, train_Y, test_Y)
    

In [21]:
from sklearn.model_selection import StratifiedKFold

accuracy_max = 0.0
accuracy_min = 100.0
accuracy_avg = 0.0

best_clf = 0

k_cross_fold = 10

skf = StratifiedKFold(n_splits=k_cross_fold)
for train_index, test_index in skf.split(X, Y):
    train_X, test_X = X[train_index], X[test_index]
    train_Y, test_Y = Y[train_index], Y[test_index]
    
    accuracy, clf = MLP(train_X, test_X, train_Y, test_Y)
    accuracy *= 100
    
    if(accuracy > accuracy_max):
        accuracy_max = accuracy
        best_clf = clf
    accuracy_min = min(accuracy_min, accuracy)
    accuracy_avg += accuracy
    
    print("#######################")
    
print("Max accuracy = " + str(accuracy_max))
print("Min accuracy = " + str(accuracy_min))
print("Avg accuracy = " + str(accuracy_avg/k_cross_fold))


(96, 9)
(96, 1)


/usr/lib64/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


95.0
Accuracy = 0.9895833333333334
#### CONFUSION MATRIX ##########
[[0.97058824 0.02941176]
 [0.         1.        ]]
#######################
(96, 9)
(96, 1)


/usr/lib64/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


94.0
Accuracy = 0.9791666666666666
#### CONFUSION MATRIX ##########
[[0.94117647 0.05882353]
 [0.         1.        ]]
#######################
(96, 9)
(96, 1)


/usr/lib64/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


93.0
Accuracy = 0.96875
#### CONFUSION MATRIX ##########
[[0.90909091 0.09090909]
 [0.         1.        ]]
#######################
(96, 9)
(96, 1)


/usr/lib64/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


96.0
Accuracy = 1.0
#### CONFUSION MATRIX ##########
[[1. 0.]
 [0. 1.]]
#######################
(96, 9)
(96, 1)


/usr/lib64/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


92.0
Accuracy = 0.9583333333333334
#### CONFUSION MATRIX ##########
[[0.87878788 0.12121212]
 [0.         1.        ]]
#######################
(96, 9)
(96, 1)


/usr/lib64/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


95.0
Accuracy = 0.9895833333333334
#### CONFUSION MATRIX ##########
[[0.96969697 0.03030303]
 [0.         1.        ]]
#######################
(96, 9)
(96, 1)


/usr/lib64/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


96.0
Accuracy = 1.0
#### CONFUSION MATRIX ##########
[[1. 0.]
 [0. 1.]]
#######################
(96, 9)
(96, 1)


/usr/lib64/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


94.0
Accuracy = 0.9791666666666666
#### CONFUSION MATRIX ##########
[[0.93939394 0.06060606]
 [0.         1.        ]]
#######################
(95, 9)
(95, 1)


/usr/lib64/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


93.0
Accuracy = 0.9789473684210527
#### CONFUSION MATRIX ##########
[[0.93939394 0.06060606]
 [0.         1.        ]]
#######################
(95, 9)
(95, 1)


/usr/lib64/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


95.0
Accuracy = 1.0
#### CONFUSION MATRIX ##########
[[1. 0.]
 [0. 1.]]
#######################
Max accuracy = 100.0
Min accuracy = 95.83333333333334
Avg accuracy = 98.43530701754386
